package com.fruit.web.model;

import com.fruit.web.model.base.BaseAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Auth extends BaseAuth<Auth> {
	public static final Auth dao = new Auth().dao();
}
