package com.fruit.web.model;

import com.fruit.web.model.base.BaseBanner;
import com.google.common.collect.Lists;
import com.jfinal.kit.StrKit;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Banner extends BaseBanner<Banner> {
	public static final Banner dao = new Banner().dao();
	private static final int STATUS_USE = 1;// 状态为使用中
	private static final int STATUS_UNUSED = 0;// 状态为未使用

	/**
	 * 根据分组key值查出符合的数据
	 * @param key
	 * @param fields	sql的select后的字段，已英文逗号分隔
	 * @return
	 */
	public List<Banner> findByGroupKey(String key, String fields) {
		if(StrKit.isBlank(key)) {
			return Lists.newArrayList();
		}
		StringBuilder sql = new StringBuilder("SELECT ");
		if(StrKit.notBlank(fields)) {
			sql.append(fields).append(" ");
		} else {
			sql.append("* ");
		}
		sql.append("FROM b_banner WHERE group_key = ? AND status = ? ORDER BY sort DESC ");
		return find(sql.toString(), key, STATUS_USE);
	}
}
