package com.fruit.web.model;

import com.fruit.web.model.base.BaseBusinessInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessInfo extends BaseBusinessInfo<BusinessInfo> {
	public static final BusinessInfo dao = new BusinessInfo().dao();
}
