package com.fruit.web.model;

import com.fruit.web.model.base.BaseBusinessAuth;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessAuth extends BaseBusinessAuth<BusinessAuth> {
	public static final BusinessAuth dao = new BusinessAuth().dao();

	/**
	 * 根据用户ID获取商户认证信息
	 */
	public List<BusinessAuth> getBusinessAuthByUid(Integer uid){
		StringBuilder sb=new StringBuilder();
		sb.append("select ba.id,ba.legal_person_name,ba.identity, ");
		sb.append("ba.bank_account,ba.business_license,auth_type, ");
		sb.append("ba.img_identity_front,ba.img_identity_reverse, ");
		sb.append("ba.img_license,ba.img_online_shop ");
		sb.append("from b_business_auth ba where ba.u_id=?");
		return find(sb.toString(),uid);
	}
}
