package com.fruit.web.model;

import com.fruit.web.model.base.BaseBusinessInfo;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessInfo extends BaseBusinessInfo<BusinessInfo> {
    public static final BusinessInfo dao = new BusinessInfo().dao();

    public List<BusinessInfo> getBusinessInfoByUid(Integer uid) {
        StringBuilder sb = new StringBuilder();
        sb.append("select bi.id,bi.business_name,bi.business_contacts, ");
        sb.append("bi.phone,bi.address_province,bi.address_city, ");
        sb.append("bi.address_detail,bi.address_shop,bi.shipments_type ");
        sb.append("from b_business_info bi where bi.u_id =?");
        return find(sb.toString(),uid);
    }
}
