package com.fruit.web.model;

import com.fruit.web.model.base.BaseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Info extends BaseInfo<Info> {
	public static final Info dao = new Info().dao();
}
