package com.fruit.web.model;

import com.fruit.web.model.base.BaseOrder;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
    public static final Order dao = new Order().dao();

    /**
     * 删除订单
     *
     * @param orderId
     */
    public void removeOrder(int orderId) {
        Db.update("delete from b_order where order_id = ? ", orderId);
    }

    /**
     * 添加订单
     *
     * @param order
     */
    public void addOrder(Order order) {
        order.save();
    }
}
