package com.fruit.web.model;

import com.fruit.web.model.base.BaseProductRecommend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductRecommend extends BaseProductRecommend<ProductRecommend> {
	public static final ProductRecommend dao = new ProductRecommend().dao();
}
