package com.fruit.web.model;

import com.fruit.web.model.base.BaseProductImg;
import com.google.common.collect.Lists;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductImg extends BaseProductImg<ProductImg> {
	public static final ProductImg dao = new ProductImg().dao();
	public static final int TYPE_PRODUCT = 1;
	public static final int TYPE_MARKET = 2;

	public List<String> getImgs(int productId, int type) {
		List<ProductImg> imgs = find("SELECT img_url FROM b_product_img WHERE product_id=? AND type=? ORDER BY sort DESC", productId, type);
		List<String> imgList = Lists.newArrayList();
		for(ProductImg img : imgs) {
			imgList.add(img.getImgUrl());
		}
		return imgList;
	}
}
