package com.fruit.web.model;

import com.fruit.web.model.base.BaseTypeGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TypeGroup extends BaseTypeGroup<TypeGroup> {
	public static final TypeGroup dao = new TypeGroup().dao();
}
