package com.fruit.web.model;

import com.fruit.web.model.base.BaseType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Type extends BaseType<Type> {
	public static final Type dao = new Type().dao();

	public static final int STATUS_ENABLE = 1;
	public static final int STATUS_DISABLE = 0;
}
