package com.fruit.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusinessAuth<M extends BaseBusinessAuth<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setLegalPersonName(java.lang.String legalPersonName) {
		set("legal_person_name", legalPersonName);
	}

	public java.lang.String getLegalPersonName() {
		return getStr("legal_person_name");
	}

	public void setIdentity(java.lang.String identity) {
		set("identity", identity);
	}

	public java.lang.String getIdentity() {
		return getStr("identity");
	}

	public void setBankAccount(java.lang.String bankAccount) {
		set("bank_account", bankAccount);
	}

	public java.lang.String getBankAccount() {
		return getStr("bank_account");
	}

	public void setBusinessLicense(java.lang.String businessLicense) {
		set("business_license", businessLicense);
	}

	public java.lang.String getBusinessLicense() {
		return getStr("business_license");
	}

	public void setAuthType(java.lang.String authType) {
		set("auth_type", authType);
	}

	public java.lang.String getAuthType() {
		return getStr("auth_type");
	}

	public void setImgIdentityFront(java.lang.String imgIdentityFront) {
		set("img_identity_front", imgIdentityFront);
	}

	public java.lang.String getImgIdentityFront() {
		return getStr("img_identity_front");
	}

	public void setImgIdentityReverse(java.lang.String imgIdentityReverse) {
		set("img_identity_reverse", imgIdentityReverse);
	}

	public java.lang.String getImgIdentityReverse() {
		return getStr("img_identity_reverse");
	}

	public void setImgLicense(java.lang.String imgLicense) {
		set("img_license", imgLicense);
	}

	public java.lang.String getImgLicense() {
		return getStr("img_license");
	}

	public void setImgOnlineShop(java.lang.String imgOnlineShop) {
		set("img_online_shop", imgOnlineShop);
	}

	public java.lang.String getImgOnlineShop() {
		return getStr("img_online_shop");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
