package com.fruit.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseParam<M extends BaseParam<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setBeforeNodeId(java.lang.Integer beforeNodeId) {
		set("Before_node_id", beforeNodeId);
	}

	public java.lang.Integer getBeforeNodeId() {
		return getInt("Before_node_id");
	}

	public void setParamName(java.lang.String paramName) {
		set("param_name", paramName);
	}

	public java.lang.String getParamName() {
		return getStr("param_name");
	}

	public void setParam(java.lang.String param) {
		set("param", param);
	}

	public java.lang.String getParam() {
		return getStr("param");
	}

	public void setKey(java.lang.String key) {
		set("key", key);
	}

	public java.lang.String getKey() {
		return getStr("key");
	}

	public void setDescribe(java.lang.String describe) {
		set("describe", describe);
	}

	public java.lang.String getDescribe() {
		return getStr("describe");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
