package com.fruit.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProductMarket<M extends BaseProductMarket<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setProductId(java.lang.Integer productId) {
		set("product_id", productId);
	}

	public java.lang.Integer getProductId() {
		return getInt("product_id");
	}

	public void setBuySuggest(java.lang.String buySuggest) {
		set("buy_suggest", buySuggest);
	}

	public java.lang.String getBuySuggest() {
		return getStr("buy_suggest");
	}

	public void setMarketFeedback(java.lang.Integer marketFeedback) {
		set("market_feedback", marketFeedback);
	}

	public java.lang.Integer getMarketFeedback() {
		return getInt("market_feedback");
	}

	public void setSupplyGoods(java.lang.Integer supplyGoods) {
		set("supply_goods", supplyGoods);
	}

	public java.lang.Integer getSupplyGoods() {
		return getInt("supply_goods");
	}

	public void setFruitDes(java.lang.String fruitDes) {
		set("fruit_des", fruitDes);
	}

	public java.lang.String getFruitDes() {
		return getStr("fruit_des");
	}

	public void setSupportDes(java.lang.String supportDes) {
		set("support_des", supportDes);
	}

	public java.lang.String getSupportDes() {
		return getStr("support_des");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setLastEditUserId(java.lang.Integer lastEditUserId) {
		set("last_edit_user_id", lastEditUserId);
	}

	public java.lang.Integer getLastEditUserId() {
		return getInt("last_edit_user_id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
